### ISSUE TITLE
docker-compose.yaml' is invalid

### ISSUE THREAD

**Issue by krouser** [detectify/Varnish-H2-Request-Smuggling#1]
i get this error when i run the docker-compose up command

ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services: 'varnishncsa'
Unsupported config option for volumes: 'workdir' (did you mean 'working_dir'?)

**Comment by AlfredBerg** [comment]
Hey!
I'm not able to reproduce this, but seems like not specifying the docker-compose version could be the reason. I have updated docker compose file, could you give it another try and see if that solved this?

**Comment by krouser** [comment]
thanks works, i upgraded the docker-compose binary on my kali machine.

1. sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

2. sudo chmod +x /usr/local/bin/docker-compose
