### ISSUE TITLE
ssl

### ISSUE THREAD

**Issue by rotil** [detectify/Varnish-H2-Request-Smuggling#2]
hi guys 
thank you for the lab but it's on HTTP
and burp dos not send H2 on HTTP only HTTPS.

**Comment by AlfredBerg** [comment]
Hey,
You have to use hitch that is at port 443 that terminates the HTTPS. You can find more information here: https://labs.detectify.com/2021/08/26/how-to-set-up-docker-for-varnish-http-2-request-smuggling/

**Comment by cryptoluks** [comment]
For me, the hitch container occasionally quits after starting with `docker-compose up`. Invoking the hitch container manually with `docker start <container id>` solves it.
